package gcore

import "errors"

var (
	ErrBufferTooSmall                   = errors.New("buffer is too small")
	ErrReadFailed                       = errors.New("gr_read failed")
	ErrReplyTo                          = errors.New("gr_reply_to failed")
	ErrSendFailed                       = errors.New("gr_send failed")
	ErrReplyDepositFailed               = errors.New("gr_reply_deposit failed")
	ErrWakeFailed                       = errors.New("gr_wake failed")
	ErrReserveGasFailed                 = errors.New("gr_reserve_gas failed")
	ErrUnreserveGasFailed               = errors.New("gr_unreserve_gas failed")
	ErrSystemReserveGasFailed           = errors.New("gr_system_reserve_gas failed")
	ErrReplyCodeFailed                  = errors.New("gr_reply_code failed")
	ErrSignalCodeFailed                 = errors.New("gr_signal_code failed")
	ErrUnsupportedSignalCode            = errors.New("unsupported signal code")
	ErrReplyFromReservationFailed       = errors.New("gr_reservation_reply failed")
	ErrReplyWithGasFailed               = errors.New("gr_reply_wgas failed")
	ErrReplyCommitFailed                = errors.New("gr_reply_commit failed")
	ErrReplyPushFailed                  = errors.New("gr_reply_push failed")
	ErrReplyCommitWithGasFailed         = errors.New("gr_reply_commit_wgas failed")
	ErrReplyCommitFromReservationFailed = errors.New("gr_reservation_reply_commit failed")
	ErrReplyInputFailed                 = errors.New("gr_reply_input failed")
	ErrReplyPushInputFailed             = errors.New("gr_reply_push_input failed")
	ErrReplyInputWithGasFailed          = errors.New("gr_reply_input_wgas failed")
	ErrSendInputFailed                  = errors.New("gr_send_input failed")
	ErrSendFromReservationFailed        = errors.New("gr_reservation_send failed")
	ErrSendInitFailed                   = errors.New("gr_send_init failed")
	ErrSendPushInputFailed              = errors.New("gr_send_push_input failed")
	ErrSendCommitFailed                 = errors.New("gr_send_commit failed")
	ErrSendInputWithGasFailed           = errors.New("gr_send_input_wgas failed")
	ErrSendCommitFromReservationFailed  = errors.New("gr_reservation_send_commit failed")
)
